### ISSUE TITLE
4.110 issue

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#101]
Seeing hoobsd failing post install at --configure ![image](https://user-images.githubusercontent.com/23066923/138007145-b28e5420-89ab-4ef2-afb6-440438173c94.png)

**Comment by mkellsy** [comment]
Run this.
```
sudo apt-get update
apt-get --reinstall install hoobsd hoobs-cli hoobs-gui
```

**Comment by themick4u** [comment]
Still erroring out

**Comment by mkellsy** [comment]
Is this Marv? Or are you working with Marv.
I am writing something up on Slack for this.

**Comment by mkellsy** [comment]
I missed the **sudo** on the apt-get install command. it's late for me
```
sudo apt-get update
sudo apt-get --reinstall install hoobsd hoobs-cli hoobs-gui
```

**Comment by themick4u** [comment]
I retried it and it still errors out in same dpkg place for —configure

**Comment by themick4u** [comment]
No, it’s buster image on rPi 4

**Comment by mkellsy** [comment]
OK try running these commands.
```
sudo dpkg --configure -a
sudo apt remove hoobsd
wget -qO- https://dl.hoobs.org/stable | sudo bash -
sudo apt install hoobsd hoobs-cli hoobs-gui
sudo hoobsd service restart
```

**Comment by themick4u** [comment]
Thanks, removing and reinstalling hoobsd did the trick

**Comment by themick4u** [comment]
So it shows I am on version 4.1.9. That is the current correct version right?

**Comment by mkellsy** [comment]
Yep, that's the latest.
