### ISSUE TITLE
Can't upgrade anymore even of fresh install

### ISSUE THREAD

**Issue by GoalTV** [hoobs-org/hoobsd#102]
I can't upgrade to new version of hoobs I even got new img file from hoobs official website and did fresh install and it still fail

Setting up hoobsd (4.0.110) ...
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 29.77s.
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done
error executing command
dpkg: error processing package hoobsd (--configure):
 installed hoobsd package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of hoobs-gui:
 hoobs-gui depends on hoobsd (>= 4.0.0); however:
  Package hoobsd is not configured yet.

dpkg: error processing package hoobs-gui (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hoobsd
 hoobs-gui
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by GoalTV** [comment]
Fixed I followed this

https://github.com/hoobs-org/HOOBS/issues/1549#issuecomment-932203688

Before running 
sudo apt full-upgrade

You need also install this
sudo apt install gcc-8-base

To upgrade to Raspbian 11 and after upgrade I followed this

https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

And everything is working fine now on latest hoobs version

**Comment by GoalTV** [comment]
RE:

another solution is if you don't want to upgrade is

cd
npm install eiows
cd node_modules/
sudo cp -r eiows/ /usr/lib/hoobsd/node_modules/

**Comment by mkellsy** [comment]
We have a Node 16 version coming out in a few weeks. We have to wait for the masses to upgrade to 4.1.15 before we push Node 16. If you don't want to wait. You can switch to the edge branch.
```
sudo hbs system edge
```

Be warned, we push updates to the branch much faster and the updates aren't always guarantied to work. Basically use at your own risk :)
