### ISSUE TITLE
Bridges Not Shutting Down Properly

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#13]
Bridges were running fine before updating to 4.0.28 from 4.0.27 (not related to this update, it happened before too)
Then after update was complete, bridges are stuck in restart loop with port already in use. I know rebooting will fix this but this is a recurring issue. 

![image](https://user-images.githubusercontent.com/3981552/111094904-a0495c80-8512-11eb-808b-4a55db073d87.png)

**Comment by mkellsy** [comment]
Fixed in 4.0.29
