### ISSUE TITLE
Auto Restart Makes it Imposable to Shutdown Crashing Bridges

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#14]
No Stop option available
![image](https://user-images.githubusercontent.com/3981552/111094714-3cbf2f00-8512-11eb-98df-261e41af3420.png)

Bridge stuck in restart loop due to a plugin error

![image](https://user-images.githubusercontent.com/3981552/111094741-4cd70e80-8512-11eb-95b7-354153adf2d4.png)

**Comment by mkellsy** [comment]
Fixed in 4.0.29
