### ISSUE TITLE
Make Public Instance Loader

### ISSUE THREAD

**Issue by bwp91** [hoobs-org/hoobsd#15]
When I SSH into hoobs I get this message:

```
...
To configure HOOBS browse to the one of the following addresses from another 
device on your network:

* http://hoobs
* http://#.#.#.### (redacted)


HOOBS and the HOOBS logo are registered trademarks of HOOBS Inc.
Copyright (C) 2020 HOOBS Inc. All rights reserved.
...
```

I see `.local` was removed in this commit https://github.com/hoobs-org/HOOBS/commit/d477b1bc1221eee2236d2b27c38dec556371ce09 but why was it removed?

When I visit `http://hoobs` in my browser it says page not found and I have to append `.local` to the address

**Comment by mkellsy** [comment]
50% of the devices out there need .local
50% wont work with .local

It's a problem.

I am planning on making a scanner at https://console.hoobs.org
that will scan your local network and find HOOBS instances and list them
if only one is found it will redirect to it

I am tired of answering the hoobs.local wont work issue :)

**Comment by bwp91** [comment]
> I am tired of answering the hoobs.local won't work issue

Sorry didn’t realise this had been asked before.

**Comment by mkellsy** [comment]
Reopening. Still need to make the scanner at https://console.hoobs.org

**Comment by mkellsy** [comment]
Did some research, web pages can not easily scan a local network.
I can make requests, but I can't get the subnets, and I can't get the MAC address.
There are security hurdles for this.

I am ditching this project, and this is solved by HOOBS Desktop and HOOBS Mobile.
