### ISSUE TITLE
hoobs.local:9090

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/hoobsd#16]
if entered these commands in terminal

npm i homebridge-hue
sudo npm i -g --unsafe-perm homebridge-ring

both installs without issues but not visible in hoobs.
i did so because these commands stands in plugin description
Some users will do it like that

**Comment by mkellsy** [comment]
Not blocking that.
1. Doesn't use NPM
2. We have our own CLI now

Won't fix
