### ISSUE TITLE
Auto Save HUE Users

### ISSUE THREAD

**Issue by oliverchapple** [hoobs-org/hoobsd#17]
hi 

all works well 

but I think I found a bug on the hue bridge when  you shutdown or restart you have to press the button on the hue bridge to link it.

thanks Oliver

**Comment by mkellsy** [comment]
There is a log entry from that plugin that gives you the user token.

Take that and add a user in the config.

I am thinking of a way to auto save that with encrypted config files.

**Comment by oliverchapple** [comment]
that's sounds good
