### ISSUE TITLE
Tplink Smarthome Plugin Out of Memory

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#24]
This is a recurring issue on a fresh install of the latest version. It runs fine for a few minutes then it starts giving Timeout errors and then it gives a heap out of memory error and crashes the bridge. This only happens in HOOBS 4. 

![image](https://user-images.githubusercontent.com/3981552/113083453-3b486480-91aa-11eb-8cd9-c04f078459ab.png)

**Comment by cstack1234** [comment]
Same issue here

**Comment by mkellsy** [comment]
This might be related to #30 
I am pausing until tested in 4.0.39

**Comment by cstack1234** [comment]
I removed it from Hoobs 4 and added it back to Hoobs 3.

**Comment by mkellsy** [comment]
How is the memory in 4.0.40

**Comment by mkellsy** [comment]
Fixed and confirmed in issue #33
