### ISSUE TITLE
Port already in use

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#26]
1. Had 2 separate bridges running already (one with tplink and one with camera-ffmpeg plugin).
2. Installed myq on its own bridge, got the following logs
![image](https://user-images.githubusercontent.com/3981552/113227285-4f4e9d80-9260-11eb-8b0d-f70d30ad6f44.png)

It stopped on its own after installation then restarted after adding configuration and stopped again. I then manually started it from the bridge page and now it's running. Not sure what caused this so opening this for investigation.

**Comment by askovi** [comment]
I think what happened is that the bridge creator during the plugin installed pre-populated the port input with a port already in use by one of the 2 other bridges.

**Comment by ballakers** [comment]
I think I’m having a similar issue. Except after about a minute the UI just goes to the loading screen and then the Pi drops off the network completely and the recovery webpage and SSH doesn’t work either of course so I can’t even grab any logs. Ring plugin always works whether I install and spawn a new bridge or add to empty bridge. I did the same with Ford Pass and it crashed when it spawned a new second bridge but when I added it to a second empty bridge it worked (on the second re-image - plugin didn’t work though) and then I added Hue and auto spawned the third bridge and then boom Pi dropped off the network again after about 3 or 4 mins after installing hue plugin (didn’t even have time to press the link button) Pi is connected via Ethernet. Would love to supply logs but I just can’t get em haha.

**Comment by themick4u** [comment]
I have a port in use error also, however, I only created a single bridge. I run hubitat-makerapi, dummy-switches, myQ and camera-ffmpeg at the moment

**Comment by ballakers** [comment]
I made sure it’s not using same bridge port as HomeAssistant’s homekit integration or HomeBridge but do native home hubs like lutron or hue use the same bridge port type linkage and if so how can we ensure we don’t overlap those bridge ports by accident.

**Comment by askovi** [comment]
This seems to also occur when playing around with the bridge settings such as Generate New Identifier, changing the Bridge Advertiser, etc.

**Comment by mkellsy** [comment]
The bridges weren't shutting down properly. I have this fixed in 4.0.39.

**Comment by mkellsy** [comment]
Related to #30
