### ISSUE TITLE
FordPass not Installing

### ISSUE THREAD

**Issue by ballakers** [hoobs-org/hoobsd#27]
Because of my previous issues I started by adding three blank bridges with my self-assigned unique homekit code and bridge port number (ensuring they are all different and dont overlap with any other bridge ports outside of hoobs also.  All three added fine.   Added Hue plug-in first and the 4-non-homekit lights showed up after connecting without having to delete and re-add bridge.  For the 2nd and 3rd bridges after adding plugins Ring and Dummy didn't populate any devices in the home app, went to settings in the app and both bridges said not responding.  Worked fine after removing and re-adding bridges to the app - devices populated and things are working fine for now.  No errors in logs except for the usually Hue heartbeat / drift warnings.

 Tempted to try Ford Pass again by adding to a fourth pre-created empty bridge hoping it wont trigger the issues previous where the Pi goes completely offline (router confirmed this).

**Comment by mkellsy** [comment]
Related to #30

**Comment by mkellsy** [comment]
The bridges weren't shutting down properly. I have this fixed in 4.0.39.

**Comment by mkellsy** [comment]
I think this has been fixed. Please upgrade to 4.0.42
You will need co clear bridge caches after this upgrade due to another bug fix.

Let me know if this is working.

**Comment by mkellsy** [comment]
Stale (1 week no follow-up)
I am able to install  FordPass in development,

> I can't fully test because I have a GMC and and Audi, no Ford.
