### ISSUE TITLE
Bridge Doesn't Properly Reset the Identifier

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#29]
If you reset bridge identifier, or delete the entire cache and try to re-pair the bridge in Homekit it won't allow it. It keeps the same 4 digits number associated with the bridge and Homekit reports an 'Invalid security check or Action not allowed' error. The bridge must first be deleted from Homekit, then re-added with the new identifier, meaning Homekit recognizes is as the same bridge but with some different data therefore showing the invalid security check error.

**Comment by mkellsy** [comment]
Complete cache purge now regenerates the bridge username. Overlooked this because this information has moved in HOOBS 4.

Fixed in 4.0.39
