### ISSUE TITLE
Bridge Shutdown not Firing

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#30]
This one is very weird. I got a bunch of bridges setup, everything works in the HOOBS dashboard, accessories are controllable, no issues in the logs. Bridges are added to Homekit and work. Then if I reboot the device from Hub Settings, all accessories stop working in Homekit. However they work fine in the HOOBS dashboard and no errors in the logs. This can only be fixed by regenerating the bridge identifier, removing the bridge from Homekit and re-adding it. Then it works until next reboot and it happens again. It's currently reproducible. It affects all bridges.

**Comment by askovi** [comment]
So I'm currently able to reproduce. 
1. If I reboot the device all bridges stop working in Homekit but work fine in the HOOBS dashboard.
2. If I remove a bridge from Homekit then re-scan the code to re-add it (without changing anything about the bridge) it works again in Homekit until device reboot. 
3. Tested with both Bonjour and Ciao advertiser, same thing.

**Comment by themick4u** [comment]
I am experiencing this too with both the hubitat makerapi plugin and also the hubitat tonesto7 plugin riding on their own seperate bridges (at different hoob setups)

**Comment by themick4u** [comment]
Also experiencing this with cameras-ffmpeg plugin on its own bridge as well... Cameras do not come back online after reboot.

**Comment by mkellsy** [comment]
What I think is happening here is the bridge shutdown is not being triggered. I am looking into what's happening.

**Comment by mkellsy** [comment]
The bridges weren't shutting down properly. I have this fixed in 4.0.39.

**Comment by themick4u** [comment]
> 
> 
> The bridges weren't shutting down properly. I have this fixed in 4.0.39.

Michael, where can we get the 4.0.39 (if available)? I am not seeing it show up in updates.

**Comment by mkellsy** [comment]
It's in development. 4.0.39 is not released yet.

**Comment by themick4u** [comment]
10-4 understood

**Comment by themick4u** [comment]
So I see the .39 came out and I applied it. I removed one bridge and added a new bridge to join the other three I had left untouched. Following reboot, new bridge added stayed intact while the 3 others needed to be removed and readded to HomeKit

**Comment by mkellsy** [comment]
The bridges are shutting down properly. This has been confirmed by many.
