### ISSUE TITLE
Errors in logs (unsure what exactly it is)

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#32]
3/31/2021, 7:40:58 PMHOOBs-4Registering accessory 'homebridge-dummy.DummySwitch'
3/31/2021, 7:40:58 PMHOOBs-4Loaded plugin 'homebridge-hubitat-makerapi'
3/31/2021, 7:40:58 PMHOOBs-4Bridge Version: 2.7
3/31/2021, 7:40:58 PMHOOBs-4Plugin Version: 0.4.14
3/31/2021, 7:40:58 PMHOOBs-4Registering platform 'homebridge-hubitat-makerapi.Hubitat-MakerAPI'
3/31/2021, 7:40:58 PMHOOBs-4Loaded plugin 'homebridge-myq'
3/31/2021, 7:40:58 PMHOOBs-4Registering platform 'homebridge-myq.myQ'
3/31/2021, 7:40:58 PMHOOBs-4Loading 3 platforms...
3/31/2021, 7:40:58 PMHOOBs-4Loading 2 accessories...
3/31/2021, 7:40:58 PMHOOBs-4Preparing Advertiser for 'HOOBs-4 32FE' using bonjour-hap backend!
3/31/2021, 7:40:59 PMHOOBs-4ERRORError: listen EADDRINUSE: address already in use 0.0.0.0:51826 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:325:21) at Server.start (/usr/src/bridge/server.ts:251:14)
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:41:05 PMHOOBs-4WARNINGunhandled rejection: TypeError: Cannot read property 'forEach' of undefined
3/31/2021, 7:43:28 PMHOOBs-4Configuration change
3/31/2021, 7:43:28 PMhoobs-4 stopping
3/31/2021, 7:43:28 PMHOOBs-4Configuration change
3/31/2021, 7:43:28 PMHOOBs-4 starting
3/31/2021, 7:43:28 PMHOOBs-4Configuration change
3/31/2021, 7:43:28 PMhoobs-4 stopping
3/31/2021, 7:43:33 PMHOOBs-4 starting
3/31/2021, 7:43:36 PMHOOBs-4ERRORuncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:51826
3/31/2021, 7:43:36 PMHOOBs-4ERRORuncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:51826
3/31/2021, 7:43:35 PMHOOBs-4Loaded plugin 'homebridge-camera-ffmpeg'
3/31/2021, 7:43:35 PMHOOBs-4Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
3/31/2021, 7:43:35 PMHOOBs-4Loaded plugin 'homebridge-dummy'
3/31/2021, 7:43:35 PMHOOBs-4Registering accessory 'homebridge-dummy.DummySwitch'
3/31/2021, 7:43:35 PMHOOBs-4Loaded plugin 'homebridge-hubitat-makerapi'
3/31/2021, 7:43:35 PMHOOBs-4Bridge Version: 2.7
3/31/2021, 7:43:35 PMHOOBs-4Plugin Version: 0.4.14
3/31/2021, 7:43:35 PMHOOBs-4Registering platform 'homebridge-hubitat-makerapi.Hubitat-MakerAPI'
3/31/2021, 7:43:35 PMHOOBs-4Loading 2 platforms...
3/31/2021, 7:43:36 PMHOOBs-4Loading 2 accessories...
3/31/2021, 7:43:36 PMHOOBs-4Failed to find plugin to handle accessory Garage Door
3/31/2021, 7:43:36 PMHOOBs-4Preparing Advertiser for 'HOOBs-4 32FE' using bonjour-hap backend!
3/31/2021, 7:43:36 PMHOOBs-4ERRORError: listen EADDRINUSE: address already in use 0.0.0.0:51826 at Server.setupListenHandle [as _listen2] (net.js:1318:16) at listenInCluster (net.js:1366:12) at Server.listen (net.js:1452:7) at EventedHTTPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20) at HAPServer.listen (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21) at Bridge.Accessory.publish (/usr/lib/hoobsd/node_modules/hap-nodejs/src/lib/Accessory.ts:1231:18) at Server.publishBridge (/usr/src/bridge/server.ts:325:21) at Server.start (/usr/src/bridge/server.ts:251:14)

Thank you, and have a great day!

 

Mick Jacobson

**Comment by mkellsy** [comment]
Related to #30

**Comment by themick4u** [comment]
Mike, let me know when you update the repo with 4.0.39....
