### ISSUE TITLE
Review Memory Use

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/hoobsd#33]
Hi Guys

I have been monitoring the Mem use as over the past few days I have been running the beta, I have noticed a steady increase. I rebooted yesterday and I sat around 416mb being used. 10 hours later and it is sat at 524mb which seemed excessive. Just rebooted using the new update process (Node and EWElink, excellent work btw, love the new process) and its back down to 418. I suspect a badly coded plugin, but wanted to bring this to your attention in case there is anything else...... happy to supply anything you need for diagnostics

**Comment by askovi** [comment]
@Biggsylad please post a list of all your plugins. You can get this list as a copy pastabale table from the HOOBS terminal. Type this:

`sudo hbs plugin list`

**Comment by Biggsylad** [comment]
![73E83117-E59D-4308-B10F-75C5EB0DA35E](https://user-images.githubusercontent.com/81716268/114044087-cd253100-987e-11eb-9ac1-0528f8bb0f2d.jpeg)

**Comment by askovi** [comment]
Here are mine

```
bridge                | name                            | version | path                                                                         
-------------------------------------------------------------------------------------------------------------------------------------------------
hydrawisebridge       | @homebridge-hydrawise/@mshanemc | 2.1.14  | /var/lib/hoobs/hydrawisebridge/node_modules/@mshanemc/homebridge-hydrawise   
cameraffmpegbridge    | homebridge-camera-ffmpeg        | 3.1.2   | /var/lib/hoobs/cameraffmpegbridge/node_modules/homebridge-camera-ffmpeg      
dummybridge           | homebridge-dummy                | 0.5.0   | /var/lib/hoobs/dummybridge/node_modules/homebridge-dummy                     
envisalinkbridge      | homebridge-envisalink           | 0.2.16  | /var/lib/hoobs/envisalinkbridge/node_modules/homebridge-envisalink           
myqbridge             | homebridge-myq                  | 2.6.2   | /var/lib/hoobs/myqbridge/node_modules/homebridge-myq                         
nestbridge            | homebridge-nest                 | 4.5.3   | /var/lib/hoobs/nestbridge/node_modules/homebridge-nest                       
nestcambridge         | homebridge-nest-cam             | 7.2.0   | /var/lib/hoobs/nestcambridge/node_modules/homebridge-nest-cam                
tplinksmarthomebridge | homebridge-tplink-smarthome     | 6.3.0   | /var/lib/hoobs/tplinksmarthomebridge/node_modules/homebridge-tplink-smarthome
webostvbridge         | homebridge-webos-tv             | 2.1.2   | /var/lib/hoobs/webostvbridge/node_modules/homebridge-webos-tv      

```

I only see nest in common.

**Comment by Biggsylad** [comment]
bridge                   | name                          | version | path                                                                              
-------------------------------------------------------------------------------------------------------------------------------------------------------
connexoonbridge          | homebridge-connexoon          | 2.1.1   | /var/lib/hoobs/connexoonbridge/node_modules/homebridge-connexoon                  
ewelinkbridge            | homebridge-ewelink            | 6.0.2   | /var/lib/hoobs/ewelinkbridge/node_modules/homebridge-ewelink                      
nestbridge               | homebridge-nest               | 4.5.3   | /var/lib/hoobs/nestbridge/node_modules/homebridge-nest                            
ringbridge               | homebridge-ring               | 9.15.6  | /var/lib/hoobs/ringbridge/node_modules/homebridge-ring                            
yalesmarthomealarmbridge | homebridge-yalesmarthomealarm | 1.0.3   | /var/lib/hoobs/yalesmarthomealarmbridge/node_modules/homebridge-yalesmarthomealarm
ringbridge               | hoobs-ring-sidecar            | 1.0.9   | /var/lib/hoobs/ringbridge/node_modules/hoobs-ring-sidecar

**Comment by saiajin** [comment]
Ok didn't see it thank you!

**Comment by mkellsy** [comment]
Updates in 4.0.40

**Comment by saiajin** [comment]
HI after updating to  4.0.41 I am still having issues with all accessories unresponsive.... after hub restarted I have to delete all my bridges from Homekit and re- add them

**Comment by mkellsy** [comment]
Confirmed with 4.0.40+
