### ISSUE TITLE
4.0.42 Assign Accessories to Dashboard

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/hoobsd#37]
Having upgraded, I noticed the accessories had stopped responding on the Dashboard, I removed them and readded but I am seeing some bizarre behaviors.  So when I drop into the accessories menu, I can see the Connexoon Garage Door. Icon appears to be correct. The moment I add that to the Dashboard it brings through the bridge rather than the device. Removing this from the dashboard, it corrupts the layout I have for accessories on the dashboard and then Connexoon bridge restarts. I assumed this was just the one plugin, but it does the same with Ring. If I add the light on the camera, it brings the bridge through and not the accessories and it repeats itself and restarts the bridge

**Comment by themick4u** [comment]
This might help you: https://github.com/hoobs-org/hoobsd/issues/35#issuecomment-818895219

**Comment by mkellsy** [comment]
Caches need to be cleared.

**Comment by Biggsylad** [comment]
Confirmed as working following Cache Clear
