### ISSUE TITLE
IPC Causing Hub Crash

### ISSUE THREAD

**Issue by saiajin** [hoobs-org/hoobsd#38]
All devices run.... but then hub becomes inaccessible for some reason.... must power cycle... having issues with Govee plugin shown in logs while running but not sure it’s the issue causing the hub to go down. Issue opened with plugin dev...

https://github.com/asednev/homebridge-plugin-govee/issues/33

Testing now with Govee bridge stopped.

**Comment by mkellsy** [comment]
I looked into this. The plugin is somehow reporting the relative humidity as a value greater then 100%.
hap-nodejs has recently fixed these warnings, so now we actually get them.

I am looking at why this is causing everything to become unresponsive. It should only affect that one bridge.

**Comment by saiajin** [comment]
Yes I have only been running for a few without the Govee bridge running... but it seems be stable without it..also I notice when I reboot the hub my SmartThings bridge must be started manually...

**Comment by saiajin** [comment]
I spoke too soon just as I'm leaving the hub went down...I will have to troubleshoot later but next suspect might be SmartThings...

**Comment by saiajin** [comment]
Still hub is completely going down with ST bridge off... trying both Govee and ST off now...

**Comment by mkellsy** [comment]
My SmartThings bridge has been running solid for 4 days. I don't think its the problem.
I am looking into the IPC backend. I think the logging is flooding the socket causing all connected clients to become unresponsive.

**Comment by saiajin** [comment]
Gotcha... well on power cycle the ST bridge is not restarted and has to be started manually.... I am trying to run the hub now without the ST or Govee bridges running....

BTW here are the plugins im running now:

<img width="392" alt="Screen Shot 2021-04-15 at 8 43 03 AM" src="https://user-images.githubusercontent.com/71667075/114898336-db1b0a80-9dc6-11eb-825c-e77c0a8bbdd6.png">

I was also having issues with running the Orbit plugin (works in non-beta Hoobs) but I removed it just to keep troubleshooting simple.

**Comment by saiajin** [comment]
BTW:  when I was running the Govee bridge In the most recent logs for the Govee plugin..I do not see the humidity exceeded warning,  this seems to be repeating over and over mostly:

Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
ERROR
(node:630) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 scanStart listeners added to [Noble]. Use emitter.setMaxListeners() to increase limit
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Govee Scan Started
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Govee Scan Started
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Govee Scan Started
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:10 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:15 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
Restart Discovery
4/15/2021, 8:41:20 AM
Plugin Govee Bridge
Govee
WARNING
Govee discovery stopped while Bridge is running.
4/15/2021, 8:41:25 AM
Plugin Govee Bridge stopping
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped
4/15/2021, 8:41:25 AM
Plugin Govee Bridge
Govee
Govee Scan Stopped

**Comment by saiajin** [comment]
Well I am stumped... the hub went down again  after a few hours with the Govee and SmartThings bridge disabled... do you have any other suggestions for troubleshooting?

**Comment by mkellsy** [comment]
I am working on lightening up the IPC backend.
It's the communication channel between the hub and bridge.
I think the root of your problem is in this code.

**Comment by mkellsy** [comment]
This is fixed in HOOBSD 4.0.45

**Comment by saiajin** [comment]
Appears to be stable now... will continue testing.... only Govee bridge crashing now...
