### ISSUE TITLE
Lost web interface and all Homekit connections

### ISSUE THREAD

**Issue by napthemax** [hoobs-org/hoobsd#40]
Had .44 running but suddenly I lost connection to the web interface (after a day or so) plus that it lost the Homekit integrations (get "no response").

Can still log in using CLI and running install to get latest hoobsd that updated to .45 but ended with same error as below. This is after a reboot with the hope of that it would fix the issue:

hoobs@hoobs:~ $ sudo apt install -y hoobsd hoobs-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
hoobs-cli is already the newest version (4.0.19).
hoobsd is already the newest version (4.0.45).
The following package was automatically installed and is no longer required:
  libbrotli1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up hoobsd (4.0.45) ...
yarn install v1.22.5
Segmentation fault
dpkg: error processing package hoobsd (--configure):
 installed hoobsd package post-installation script subprocess returned error exit status 139
Setting up hoobs-cli (4.0.19) ...
yarn install v1.22.5
Segmentation fault
dpkg: error processing package hoobs-cli (--configure):
 installed hoobs-cli package post-installation script subprocess returned error exit status 139
dpkg: dependency problems prevent configuration of hoobs-gui:
 hoobs-gui depends on hoobsd (>= 4.0.0); however:
  Package hoobsd is not configured yet.

dpkg: error processing package hoobs-gui (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 hoobsd
 hoobs-cli
 hoobs-gui
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by napthemax** [comment]
... and this ...

hoobs@hoobs:~ $ sudo hbs install
Segmentation fault
hoobs@hoobs:~ $

**Comment by mkellsy** [comment]
There are some issues with the image.
You will need to download the latest image.
https://repo.hoobs.org/image/hoobs-latest.zip

You should be able take a backup before re-flashing

Fixed in IMAGE 4.0.17

**Comment by napthemax** [comment]
> There are some issues with the image.
> You will need to download the latest image.
> https://repo.hoobs.org/image/hoobs-latest.zip
> 
> You should be able take a backup before re-flashing
> 
> Fixed in IMAGE 4.0.17

Ok. I just have been doing update through the GUI, but I'll flash a new one. Thanks.

**Comment by mkellsy** [comment]
Sorry for this, just ironing out the bugs before release.
Going forward, upgrading is fine.

**Comment by napthemax** [comment]
> Sorry for this, just ironing out the bugs before release.
> Going forward, upgrading is fine.

No problem. That’s going beta in a nutshell. Don’t know how many times I have added my bridges and assigned my devices over the years … If not being prepared doing that, I probably need to invest in 100% HomeKit! 😁
