### ISSUE TITLE
Do we not have accessory logging via plugins in the hoobsd log?

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#46]
I just wanted to find out if we were going to get accessory logs populating within the logs of hoobsd. My example is running hubitat-maker-api on its own bridge and in the 3.xx versions and prior, I would be able to see everything in the logs.... Now I just see that the bridge has started but nothing more. Maybe this is by design or maybe the plugin maker might need to update.

**Comment by themick4u** [comment]
Great, and thanks for the info and education on this








Thank you, and have a great day!

 

Mick
 

    On Thursday, April 22, 2021, 10:34:06 AM EDT, Michael Kellsy ***@***.***> wrote:  
 
 


There are a few plugins out there that use Watson. (a logger outside Homebridge) Hubitat and SmartThings is a few of them.

In HOOBS 4 there is a hub and many bridges. Because of this the log from each bridge needs to be sent to the hub. The bridge doesn't actually have a console.

I don't know why they use a different logger instead of the one in Homebridge. Anyway, I know of the issue and am trying to find a way to capture the output from Watson and send it to the hub.

I am marking this closed because I already have this in my roadmap, it's a very well known issue.

**Comment by mkellsy** [comment]
I was able to capture Winston's socket logging by piping the bridge's console to a custom stream that ties into our logger.

Fixed in
HOOBSD - 4.0.50
