### ISSUE TITLE
Review Un-Bridged Accessories

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#47]
Steps to reproduce an interface crash:

1. Install a plugin with unbridged accessories on a new bridge such as webostv or nestcam (i believe accessories must exist for this to happen)
2. The accessories page now stops loading while that bridge is running. (separate bug)
3. Without shutting down that bridge, go and install camera-ffmpeg on a new bridge
4. The installation modal will get to the following logs 
```
4/22/2021, 4:31:29 PM├─ through2@2.0.5
4/22/2021, 4:31:29 PM├─ to-absolute-glob@2.0.2
4/22/2021, 4:31:29 PM├─ typedarray@0.0.6
4/22/2021, 4:31:29 PM├─ unc-path-regex@0.1.2
4/22/2021, 4:31:29 PM├─ unique-stream@2.3.1
4/22/2021, 4:31:29 PM├─ util-deprecate@1.0.2
4/22/2021, 4:31:29 PM├─ ws@7.4.5
4/22/2021, 4:31:29 PM└─ xtend@4.0.2
4/22/2021, 4:31:29 PM Done in 6.95s.
4/22/2021, 4:31:31 PM cameraffmpegbridge stopping
4/22/2021, 4:31:41 PM Camera FFmpeg Bridge starting

```
5. The installation modal will never disappear
6. The entire interface becomes unresponsive, page cannot be reloaded.

**Comment by mkellsy** [comment]
Already working on this. Actually a duplicate.

**Comment by mkellsy** [comment]
Still happening in 4.0.50

**Comment by mkellsy** [comment]
I think this has to do with the room layout logic.

**Comment by mkellsy** [comment]
Camera ffmpeg in my dev environment and production are unbridged.
I am actually unable to reproduce.

Also there are multiple issues reported in one issue.
My head is spinning just trying to understand what the issue actually is.

Plugin install dialog not going away?
Is the bridge page not loading?
Are the accessories not loading?

Missing ACTUAL vs EXPECTED.
