### ISSUE TITLE
Ring Not Showing Multiple Accessories

### ISSUE THREAD

**Issue by kzoojason76** [hoobs-org/hoobsd#48]
Installed the Ring Plugin on Hoobs 4.0.49.  There should be one doorbell cam, and one spotlight cam.  Both of these cams show up in HomeKit, but I'm only seeing the doorbell cam on the Accessories Page in HOOBS.

[log.txt](https://github.com/hoobs-org/gui/files/6360315/log.txt)

**Comment by mkellsy** [comment]
I think this has to do with HB and not clearing the HOOBS accessory cache on platform accessory load.

I added some logic that will dump the HOOBS accessory cache when HB adds an accessory.

Marking fixed in
HOOBSD 4.0.50
