### ISSUE TITLE
Keep bridge status as manually set

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#49]
If you stop a bridge manually for testing other stuff and then you install a new plugin on a new bridge or remove an existing plugin from another bridge, all the manually stopped bridges start back up automatically on their own. All bridges manually stopped should remain stopped until they're turned back on or a reboot happens.

**Comment by mkellsy** [comment]
Bridges are designed to be sticky.
Now re-writing this.

Marking as wont fix and back burner.
Will review only if we get a request for this from outside testing.
