### ISSUE TITLE
Hubitat maker plugin errors (only with alarm States)

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#50]
Not sure if this is something that you can look at but am getting these errors in logs...

(undefined)
Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)
Dummy BridgeLockSetting switch to true
Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)
Dummy BridgeLockSetting switch to false
Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)
Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)

**Comment by mkellsy** [comment]
Fixed in HOOBSD 4.0.51

**Comment by themick4u** [comment]
Mike, looks like this creeped back in on latest update: Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Target State] characteristic value expected valid finite number and received "undefined" (undefined)
Hubitat Maker API BridgeERROR[Hubitat Maker API Bridge 132D@Alarm System Hubitat MakerAPI@@Security System Current State] characteristic value expected valid finite number and received "undefined" (undefined)

**Comment by themick4u** [comment]
Also Mike, I took your suggestion and gave the other tonesto-hubitat certified plugin a try and found it to be less responsive than the hubitat-makerapi plugin. I even had troubles with the post/get for my door lock states whereas the makerapi plugin works without issue. i'll bring this up on the plugin site page as well.
