### ISSUE TITLE
Light Precedence shouldn't Be Higher then Camera

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/hoobsd#54]
Hi Guys

Might be missing something here, but just rolled in 4.0.54 and spotted the new feature for snapshots for Ring Cameras. Absolutely love that, but I noticed of the 5 cameras I have I am only seeing three. Checked for any hidden devices and they are not there. Interestingly though, my two doorbells (one shared at another house) and the internal garage stick-up cam work perfectly. The two that arent is the rear flood and the driveway flood.  Can't see anything in the logs and cleared cache and repaired the bridge. I may have missed something but its a strange one. They all appear in HK and will stream live, so they are online and working with Hoobs

**Comment by mkellsy** [comment]
The precedence for lights were greater then cameras, cameras should take precedence, over the accessory type.

Fixed in HOOBSD 4.0.55
