### ISSUE TITLE
Some Plugins Require Insecure Mode

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#57]
Getting HAP discovery failure errors in the log for the Alexa certified plugin

4/27/2021, 3:51:12 PMAlexa BridgeAlexaERROR: HAP Discovery failed, please review config4/27/2021, 3:53:33 PMWarningdevice reboot command received4/27/2021, 3:53:33 PMCameras stopping4/27/2021, 3:53:33 PMDummy Bridge stopping4/27/2021, 3:53:33 PMAlexa Bridge stopping4/27/2021, 3:53:33 PMHubitat Maker API Bridge stopping4/27/2021, 3:53:33 PMMyQ stopping4/27/2021, 3:54:06 PMhub is running on port 804/27/2021, 3:54:08 PMCameras starting4/27/2021, 3:54:08 PMDummy Bridge starting4/27/2021, 3:54:08 PMMyQ starting4/27/2021, 3:54:08 PMHubitat Maker API Bridge starting4/27/2021, 3:54:08 PMAlexa Bridge starting4/27/2021, 3:54:11 PMDummy BridgeLoaded plugin 'homebridge-dummy'4/27/2021, 3:54:11 PMDummy BridgeLoading 2 accessories...4/27/2021, 3:54:12 PMDummy BridgeBridge is running on port 51666.4/27/2021, 3:54:13 PMCamerasLoaded plugin 'homebridge-camera-ffmpeg'4/27/2021, 3:54:13 PMCamerasLoading 1 platforms...4/27/2021, 3:54:13 PMCamerasCamera FFmpeg[Wyze Garage] Configuring unbridged accessory...4/27/2021, 3:54:13 PMMyQLoaded plugin 'homebridge-myq'4/27/2021, 3:54:13 PMMyQLoading 1 platforms...4/27/2021, 3:54:13 PMCamerasCamera FFmpeg[Logitech USB] Configuring unbridged accessory...4/27/2021, 3:54:13 PMMyQBridge is running on port 51333.4/27/2021, 3:54:13 PMCamerasWyze Garage FBB4 is running on port 35419.4/27/2021, 3:54:13 PMCamerasLogitech USB 6E67 is running on port 36315.4/27/2021, 3:54:13 PMCamerasBridge is running on port 51877.4/27/2021, 3:54:13 PMHubitat Maker API BridgeLoaded plugin 'homebridge-hubitat-makerapi'4/27/2021, 3:54:13 PMHubitat Maker API BridgeLoading 1 platforms...4/27/2021, 3:54:14 PMHubitat Maker API BridgeBridge is running on port 51844.4/27/2021, 3:54:15 PMMyQmyQmyQ API: Successfully connected to the myQ API.4/27/2021, 3:54:15 PMAlexa BridgeLoaded plugin 'homebridge-alexa'4/27/2021, 3:54:15 PMAlexa BridgeLoading 1 platforms...4/27/2021, 3:54:15 PMAlexa BridgeAlexahomebridge-alexa v0.5.34, node v14.16.1, homebridge v1.3.44/27/2021, 3:54:15 PMAlexa BridgeBridge is running on port 51222.4/27/2021, 3:54:17 PMMyQmyQmyQ API: Discovered device family garagedoor: Garage Door (serial number: CG084650AB7D, gateway: GW230024652D).4/27/2021, 3:54:17 PMMyQmyQmyQ API: Discovered device family gateway: Hub [Chamberlain Smart Garage Hub] (serial number: GW230024652D).4/27/2021, 3:54:17 PMMyQmyQGarage Door: Door position sensor detected. Enabling battery status support.4/27/2021, 3:54:51 PMAlexa BridgeAlexaERROR: HAP Discovery failed, please review config

**Comment by mkellsy** [comment]
These logs are hard to read.

HOOBS 4 log screen has a download button. Can you download the log and attach the file to this issue.

**Comment by mkellsy** [comment]
It looks like the plugin is having issues with multiple instances.
https://github.com/NorthernMan54/homebridge-alexa/issues/412

HOOBS 4 is instance based.

**Comment by mkellsy** [comment]
Actually after further reading, this plugin requires insecure mode. I changed this to secure after we didn't need it anymore. I will change this back.

**Comment by mkellsy** [comment]
Fixed in HOOBSD 4.0.58
