### ISSUE TITLE
Ring Cameras not working

### ISSUE THREAD

**Issue by saiajin** [hoobs-org/hoobsd#59]
Ring cameras show up in Hoobs accessories page but not response in Homekit... deleted the bridge and re added devices with same result.. Also I added a new ring motion sensor that is not showing in HK but shows on Hoobs accessories page....

latest Ring version...

**Comment by mkellsy** [comment]
I came across this when testing multiple devices with the Ring plugin.

HOOBS and HomeKit use the exact same functions to display the accessory. You may need to first un-pair the ring bridge from HomeKit. (Home -> Settings -> Bridges)

Then in HOOBS go to the Ring bridge screen, and clear the cache and regenerate the identifier.

**Comment by saiajin** [comment]
Thank you!
