### ISSUE TITLE
Increase Scanner Timeout

### ISSUE THREAD

**Issue by alangsam1** [hoobs-org/hoobsd#62]
I tried to run the MacOS client Version 4.0.29 (4.0.29) came in the email announcing Stage  2 for Hoops 4 in latest Big Sur. When it scans it can’t find it on my network yet when I type 10.0.0.60 in my safari browser it connects right away?

**Comment by mkellsy** [comment]
If the pi is on the same subnet it should eventually find it, you may have to rescan a few times.

Looks like I need to increase the timeout. I will also add a manual connect form.

**Comment by alangsam1** [comment]
it's on the same subnet. ige scanned like 10x. a manual entry would be great. 

Andy
561-398-9847



On May 14, 2021, at 7:57 AM, Michael Kellsy ***@***.***> wrote:

﻿
If the pi is on the same subnet it should eventually find it, you may have to rescan a few times.

Looks like I need to increase the timeout. I will also add a manual connect form.

**Comment by alangsam1** [comment]
Im happy to test. Please let me know when an update is posted.
Thanks

**Comment by mkellsy** [comment]
I increased the timeout to 7 seconds. I also added the ability to manually connect to a known IP.
This should cover any limitations of the scanner.

Done in Desktop 4.0.30.
> 4.0.30 is not released yet. I will let you know when we push the next round of updates.

**Comment by alangsam1** [comment]
Thank you!

**Comment by alangsam1** [comment]
Has this been updated so I can download just the MacOS client and test again?
