### ISSUE TITLE
Bridges restart loop 

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobsd#63]
All bridges seem to get into a restart loop every 24h due to port conflict and cannot be stopped unless device is rebooted. 
Could be a network issue but I'm not able to pinpoint it. Logs attached. 

[log-hoobs.log](https://github.com/hoobs-org/hoobsd/files/6480950/log-hoobs.log)

**Comment by mkellsy** [comment]
Set the start and end ports in your webos bridge. That should stop the port collisions. Make sure the port range doesn't include the ports of any other bridge you have.
