### ISSUE TITLE
Weather Plus installation failure Hoobs 4.0 beta

### ISSUE THREAD

**Issue by tcoombs** [hoobs-org/hoobsd#64]
I’m currently testing the 4.0 beta and all is working fine except I cannot install the Weather Plus plugin that works fine with Hoobs 3.. During the installation I get the following log messages:

Weather Plus Bridge starting
yarn add v1.22.10
info No lockfile found.
[1/4] Resolving packages...
warning homebridge-weather-plus > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > dark-sky > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning homebridge-weather-plus > request > har-validator@5.1.5: this library is no longer supported
warning homebridge-weather-plus > geo-tz > geobuf > shapefile > text-encoding@0.6.4: no longer maintained
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...

After a few more errors saying there’s a problem with my network (believe me there’s no issue with my network) the installation fails.

Looking at the log messages it seems that there are some compatibility issues, which leads me to believe it’s a plugin issue. Does this make sense?

Please could you investigate this issue?

**Comment by mkellsy** [comment]
There appears to be trouble with your network connection.
Try to install again.
You may need to re-position your Raspberry Pi.

**Comment by tcoombs** [comment]
Please reopen this bug report. There are no network errors at my location. Hoobs is directly connected to Ethernet and I have a very reliable broadband connection. I believe that during the installation process a module cannot be found which is why the "network error" message appears. Has anyone tested with Hoobs 4.0!

**Comment by mkellsy** [comment]
I have tested this on 15 different raspberry pis and 7 different VPNs. I am able to install this plugin in all cases.

The only issue I had was with 1 Pi 4B in a thick metal case. It had WiFi issues. I repositioned the case to be a few feet further from my access point, and then it was able to connect.
