### ISSUE TITLE
fsevents@2.3.2 Optional Dependency Failure (worried?)

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#66]
Not sure if this is anything to worry about but noticed this recently in one of the 4.0.6x updates....

info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.

**Comment by mkellsy** [comment]
We use a file system watcher, which supports Linux and Windows. That's just the Windows part.
