### ISSUE TITLE
Mobile version / view logs missing time/date stamp

### ISSUE THREAD

**Issue by themick4u** [hoobs-org/hoobsd#69]
The views for mobile on the logs only show the device and status without time/date stamp. (See attached screenshot)

![2021-06-09 003](https://user-images.githubusercontent.com/23066923/121429135-93d37500-c944-11eb-90f8-88879a947083.PNG)

**Comment by mkellsy** [comment]
This is by design. The mobile app will have better logs because it won’t have to be responsive.
