### ISSUE TITLE
An issue with regards to the copy / paste functionality under macOS HOOBS desktop 

### ISSUE THREAD

**Issue by Finder2021** [hoobs-org/hoobsd#72]
Dear HOOBS support team,

I find to two issues with Beta v4.0 as below.

- I try to copy the token string from a text file and paste to plugins configure file under the macOS desktop software that is not success, I need to enter the long string manually.
I can copy / Paste the same string under the webpage with Safari no issue.
I hope it can have copy / paste functionality in v4.0 official release with macOS desktop software.

- I found the response and update speed of webpage is much responsive and faster then macOS desktop software.

My macOS is v11.4 and HOOBS version is 4.0.69

Thanks for your attention.

**Comment by mkellsy** [comment]
The desktop app does support copy and paste.
To copy command+c
to paste command+p

I am creating a feature request for a context menu for copy and paste.
