### ISSUE TITLE
Cant Upgrade to latest

### ISSUE THREAD

**Issue by Biggsylad** [hoobs-org/hoobsd#77]
Hi Guys

I have this made availble to me in the past few days - 

Server Version: 4.0.70
CLI Version: 4.0.33

However, when I attempt the upgrade, all seems well with the process but loops round and reports back on the same version - 
Latest image as well, flashed about 4 weeks ago

Cheers
Mike

Logs attached - 

01/07/2021, 00:01:13 Hub upgrading cli
01/07/2021, 00:01:13 Hub [ DEBUG ] Hit:1 http://archive.raspberrypi.org/debian buster InRelease
01/07/2021, 00:01:13 Hub [ DEBUG ] Get:2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]
01/07/2021, 00:01:13 Hub [ DEBUG ] Hit:3 https://deb.nodesource.com/node_14.x buster InRelease
01/07/2021, 00:01:13 Hub [ DEBUG ] Hit:4 https://dl.yarnpkg.com/debian stable InRelease
01/07/2021, 00:01:13 Hub [ DEBUG ] Hit:5 https://repo.hoobs.org/debian buster InRelease
01/07/2021, 00:01:15 Hub [ DEBUG ] Fetched 15.0 kB in 2s (8,886 B/s)
01/07/2021, 00:01:15 Hub [ DEBUG ] Reading package lists...
01/07/2021, 00:01:18 Hub [ DEBUG ] Reading package lists...
01/07/2021, 00:01:18 Hub [ DEBUG ] Building dependency tree...
01/07/2021, 00:01:19 Hub [ DEBUG ] Reading state information...
01/07/2021, 00:01:19 Hub [ DEBUG ] hoobs-cli is already the newest version (4.0.30).
01/07/2021, 00:01:19 Hub [ DEBUG ] The following packages were automatically installed and are no longer required:
01/07/2021, 00:01:19 Hub [ DEBUG ] libbrotli1 python-colorzero
01/07/2021, 00:01:19 Hub [ DEBUG ] Use 'apt autoremove' to remove them.
01/07/2021, 00:01:19 Hub [ DEBUG ] 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
01/07/2021, 00:01:19 Hub upgrading hoobsd
01/07/2021, 00:01:20 Hub [ DEBUG ] Hit:1 http://archive.raspberrypi.org/debian buster InRelease
01/07/2021, 00:01:20 Hub [ DEBUG ] Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
01/07/2021, 00:01:20 Hub [ DEBUG ] Hit:3 https://deb.nodesource.com/node_14.x buster InRelease
01/07/2021, 00:01:20 Hub [ DEBUG ] Hit:4 https://dl.yarnpkg.com/debian stable InRelease
01/07/2021, 00:01:20 Hub [ DEBUG ] Hit:5 https://repo.hoobs.org/debian buster InRelease
01/07/2021, 00:01:21 Hub [ DEBUG ] Reading package lists...
01/07/2021, 00:01:24 Hub [ DEBUG ] Reading package lists...
01/07/2021, 00:01:24 Hub [ DEBUG ] Building dependency tree...
01/07/2021, 00:01:25 Hub [ DEBUG ] Reading state information...
01/07/2021, 00:01:26 Hub [ DEBUG ] hoobsd is already the newest version (4.0.69).
01/07/2021, 00:01:26 Hub [ DEBUG ] The following packages were automatically installed and are no longer required:
01/07/2021, 00:01:26 Hub [ DEBUG ] libbrotli1 python-colorzero
01/07/2021, 00:01:26 Hub [ DEBUG ] Use 'apt autoremove' to remove them.
01/07/2021, 00:01:26 Hub [ DEBUG ] 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
01/07/2021, 00:01:26 Hub [ WARNING ] service restart command received
01/07/2021, 00:01:28 Hub [ DEBUG ] Shutting down
01/07/2021, 00:01:28 Hub eWeLink Bridge stopping
01/07/2021, 00:01:28 Hub Ring Bridge stopping
01/07/2021, 00:01:28 Hub Yalesmarthomealarm Bridge stopping
01/07/2021, 00:01:28 Hub Connexoon Bridge stopping
01/07/2021, 00:01:28 Hub Nest Bridge stopping
01/07/2021, 00:01:32 Hub [ DEBUG ] Stopped
01/07/2021, 00:01:39 Hub hub is running on port 80
01/07/2021, 00:01:40 Hub eWeLink Bridge starting
01/07/2021, 00:01:40 Hub Ring Bridge starting
01/07/2021, 00:01:40 Hub Nest Bridge starting
01/07/2021, 00:01:41 Hub Connexoon Bridge starting
01/07/2021, 00:01:41 Hub Yalesmarthomealarm Bridge starting
01/07/2021, 00:01:42 eWeLink Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
01/07/2021, 00:01:42 Ring Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
01/07/2021, 00:01:43 Nest Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
01/07/2021, 00:01:43 eWeLink Bridge Loaded plugin 'homebridge-ewelink'
01/07/2021, 00:01:43 eWeLink Bridge [ DEBUG ] Registering platform 'homebridge-ewelink.eWeLink'
01/07/2021, 00:01:43 eWeLink Bridge Loading 1 platforms...
01/07/2021, 00:01:43 eWeLink Bridge eWeLink [v6.8.0] initialised. Syncing with eWeLink.
01/07/2021, 00:01:43 Connexoon Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
01/07/2021, 00:01:43 eWeLink Bridge [ DEBUG ] Preparing Advertiser for 'eWeLink Bridge 1582' using bonjour-hap backend!
01/07/2021, 00:01:43 eWeLink Bridge [ DEBUG ] Starting to advertise 'eWeLink Bridge 1582' using bonjour-hap backend!
01/07/2021, 00:01:43 eWeLink Bridge Bridge is running on port 51826.
01/07/2021, 00:01:44 Yalesmarthomealarm Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
01/07/2021, 00:01:45 Nest Bridge Loaded plugin 'homebridge-nest'
01/07/2021, 00:01:45 Nest Bridge [ DEBUG ] Registering platform 'homebridge-nest.Nest'
01/07/2021, 00:01:45 Nest Bridge Loading 1 platforms...
01/07/2021, 00:01:45 Nest Bridge Nest Fetching Nest devices.
01/07/2021, 00:01:45 Nest Bridge [ DEBUG ] Preparing Advertiser for 'Nest Bridge 97A6' using bonjour-hap backend!
01/07/2021, 00:01:45 Nest Bridge [ DEBUG ] Starting to advertise 'Nest Bridge 97A6' using bonjour-hap backend!
01/07/2021, 00:01:45 Nest Bridge Bridge is running on port 53826.
01/07/2021, 00:01:45 Yalesmarthomealarm Bridge Loaded plugin 'homebridge-yalesmarthomealarm'
01/07/2021, 00:01:45 Yalesmarthomealarm Bridge Loading 1 accessories...
01/07/2021, 00:01:45 Yalesmarthomealarm Bridge Yale Alarm Starting polling with an interval of 30000 ms
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge [ DEBUG ] Plugin 'homebridge-yalesmarthomealarm' tried to register with an incorrect plugin identifier: 'homebridge-YaleSmartHomeAlarm'. Please report this to the developer!
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge [ DEBUG ] Registering accessory 'homebridge-yalesmarthomealarm.YaleAlarmSystem'
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge [ DEBUG ] Preparing Advertiser for 'Yalesmarthomealarm Bridge AFE5' using bonjour-hap backend!
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge [ DEBUG ] Starting to advertise 'Yalesmarthomealarm Bridge AFE5' using bonjour-hap backend!
01/07/2021, 00:01:46 Connexoon Bridge Loaded plugin 'homebridge-connexoon'
01/07/2021, 00:01:46 Connexoon Bridge Loading 1 platforms...
01/07/2021, 00:01:46 Connexoon Bridge Somfy Connexoon Init
01/07/2021, 00:01:46 Connexoon Bridge Somfy Restoring cached accessory Garage Door
01/07/2021, 00:01:46 Connexoon Bridge [ DEBUG ] Registering platform 'homebridge-connexoon.Connexoon'
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge Bridge is running on port 55826.
01/07/2021, 00:01:46 Connexoon Bridge [ DEBUG ] Preparing Advertiser for 'Connexoon Bridge E7CB' using bonjour-hap backend!
01/07/2021, 00:01:46 Connexoon Bridge [ DEBUG ] Starting to advertise 'Connexoon Bridge E7CB' using bonjour-hap backend!
01/07/2021, 00:01:46 Connexoon Bridge Bridge is running on port 54826.
01/07/2021, 00:01:46 Yalesmarthomealarm Bridge Yale Alarm Polling noticed status change to 3, notifying devices
01/07/2021, 00:01:46 Ring Bridge Loaded plugin 'homebridge-ring'
01/07/2021, 00:01:46 Ring Bridge Loading 1 platforms...
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory 11a4093d-f819-4e89-a330-f39584e6c1e6 Front Door
01/07/2021, 00:01:46 Ring Bridge [ DEBUG ] Registering platform 'homebridge-ring.Ring'
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory  Driveway
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory  Back Garden
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory  Garage
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory  Upstairs
01/07/2021, 00:01:46 Ring Bridge Ring Configuring cached accessory Amy’s Front Door
01/07/2021, 00:01:47 Ring Bridge [ DEBUG ] Preparing Advertiser for 'Ring Bridge DB1B' using bonjour-hap backend!
01/07/2021, 00:01:47 Ring Bridge [ DEBUG ] Starting to advertise 'Ring Bridge DB1B' using bonjour-hap backend!
01/07/2021, 00:01:47 Ring Bridge Bridge is running on port 52826.
01/07/2021, 00:01:47 Connexoon Bridge Somfy Starting polling for Connexoon accessory state every 10 minute(s)
01/07/2021, 00:01:48 Connexoon Bridge Somfy Get Garage Door current position success: 0
01/07/2021, 00:01:48 Connexoon Bridge Somfy Get Garage Door target position success: 0
01/07/2021, 00:01:50 eWeLink Bridge eWeLink LAN monitoring started.
01/07/2021, 00:01:50 eWeLink Bridge eWeLink [Battery Charger] initialised and found locally with IP [192.168.86.44].
01/07/2021, 00:01:50 eWeLink Bridge eWeLink [Bathroom Extractor] initialised and found locally with IP [192.168.86.43].
01/07/2021, 00:01:50 Ring Bridge Ring Found the following locations:

**Comment by mkellsy** [comment]
We had to change our repo server to support different branches.

run this to fix the APT sources.

wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
